# Generated by Django 3.1.1 on 2020-10-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('addressLine1', models.CharField(max_length=256, null=True)),
                ('addressLine2', models.CharField(max_length=256, null=True)),
                ('placeName', models.CharField(max_length=256, null=True)),
                ('isMobilePoint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('hashedPassword', models.CharField(max_length=128)),
                ('donatedBlood', models.FloatField(default=0.0)),
                ('donatedPlasma', models.FloatField(default=0.0)),
                ('donatedPlatelets', models.FloatField(default=0.0)),
                ('lastDonationTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField(null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.localization')),
            ],
        ),
    ]
