# Generated by Django 3.1.1 on 2020-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donationType',
            field=models.CharField(choices=[('Blood', 'Bld'), ('Plasma', 'Plm'), ('Platelets', 'Plt')], default='Blood', max_length=50),
        ),
    ]
